---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Teng-Schema-Dumper-InflateColumn-DateTime
no_index:
  directory:
    - inc
    - t
resources:
  repository: git://github.com/rosiro/Teng-Schema-Dumper-InflateColumn-DateTime.git
version: undef
